### ISSUE TITLE
New AnimationStatus listener is added on each tap

### ISSUE THREAD

**Issue by Zohenn** [watery-desert/water_drop_nav_bar#4]
The way it is implemented now, each tap on the nav bar item results in new ```AnimationStatus``` listener being added. 

**To Reproduce**
1. Add a ```print(status)``` statement inside ```addStatusListener``` calback inside ```_onTap``` method of ```BuildNavBar``` widget.
2. Tap on second item, then tap on third item.

**Expected behavior**
After third tap you should see logs that look somewhat like this:
```
AnimationStatus.dismissed
AnimationStatus.forward
AnimationStatus.completed
```

**Current behavior**
It looks like this:
```
AnimationStatus.dismissed
AnimationStatus.forward
AnimationStatus.completed
AnimationStatus.completed
```
And on the next tap it will look like this:
```
AnimationStatus.dismissed
AnimationStatus.dismissed
AnimationStatus.forward
AnimationStatus.forward
AnimationStatus.completed
AnimationStatus.completed
AnimationStatus.completed
```
Since you add the listener after calling ```forward``` on ```_controller```, you will see n ```AnimationStatus.completed``` logs and n - 1 ```AnimationStatus.dismissed``` or ```AnimationStatus.forward``` logs, where n is the number of taps.

**Fix**
Remove ```addStatusListener``` from ```_onTap``` method and put it in the ```initState```.
It should look like this:
```dart
@override
void initState() {
  super.initState();
  _controller = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 800),
  )
    ..forward(from: 0.0)
    ..addStatusListener((AnimationStatus status) {
      if (status == AnimationStatus.completed) {
        _previousIndex = widget.selectedIndex;
      }
    });
}
```
You can safely assign ```widget.selectedIndex``` to ```_previousIndex```. Also, the call to ```setState``` is not needed, as the ```_previousIndex``` value won't be used to render anything until next item tap.

**Comment by watery-desert** [comment]
hmm, that listener was redundant. Thanks. But calling `setState` is necessary to update the UI. `widget.seletedIndex` is called inside `setState` from `onItemSelected` callBack function. This is why you don't need to call `setState` again here.

**Comment by Zohenn** [comment]
These are 2 separate things, if I understand you correctly. You could probably remove the listener completely and override ```didUpdateWidget```, which would check if ```widget.selectedIndex``` has changed, and if so it would set ```_previousIndex``` to the value from old widget. The current way works, so it's more of a question which approach is more correct.

On a side note, there are more things I would change in order to increase the quality of your code, just tell me if you're interested.
